#!/bin/zsh

EWW=`which eww`
eww_status_output=`eww state | xargs`

if [[ ! `pidof eww` ]]; then
	${EWW} daemon
	sleep 1
fi

if [[ ! -z "$eww_status_output" ]] then;
	${EWW} close-all
else
	${EWW} open topbar
fi
