#!/bin/zsh

EWW=/home/placidfireball/build/eww/target/release/eww
eww_status_output=`/home/placidfireball/build/eww/target/release/eww state | xargs`

if [[ ! `pidof eww` ]]; then
	${EWW} daemon
	sleep 1
fi

if [[ ! -z "$eww_status_output" ]] then;
	${EWW} close-all
else
	${EWW} open topbar
	${EWW} reload
fi
