return {
  "sudo-tee/opencode.nvim",
  dependencies = {
    "nvim-lua/plenary.nvim",
    {
      "MeanderingProgrammer/render-markdown.nvim",
      opts = {
        anti_conceal = { enabled = false },
        file_types = { 'markdown', 'opencode_output' },
      },
      ft = { 'markdown', 'Avante', 'copilot-chat', 'opencode_output' },
    },
    'saghen/blink.cmp',
    'nvim-telescope/telescope.nvim',
  },
  config = function()
    require("opencode").setup {
      preferred_picker = 'telescope',
      preferred_completion = 'blink',
      default_global_keymaps = false,
      default_mode = 'plan',
      keymap_prefix = '<leader>c',
      keymap = {
        editor = {
          ['<leader>cc'] = { 'toggle' },
          ['<leader>ci'] = { 'open_input' },
          ['<leader>co'] = { 'open_output' },
          ['<leader>ct'] = { 'toggle_focus' },
          ['<leader>cq'] = { 'close' },
          ['<leader>cs'] = { 'select_session' },
          ['<leader>cp'] = { 'configure_provider' },
          ['<leader>cgv'] = { 'add_visual_selection_inline', mode = {'v'} },
          ['<leader>cv'] = { 'paste_image'},
          ['<leader>cd'] = { 'diff_open' },
          ['<leader>c]'] = { 'diff_next' },
          ['<leader>c['] = { 'diff_prev' },
          ['<leader>cdq'] = { 'diff_close' },
          ['<leader>cdA'] = { 'diff_revert_all' },
          ['<leader>ctt'] = { 'toggle_tool_output' },
          ['<leader>ctr'] = { 'toggle_reasoning_output' },
          ['<leader>c/'] = { 'quick_chat', mode = { 'n', 'x' } },
        },
        input_window = {
          ['<CR>'] = { 'submit_input_prompt', mode = { 'n', 'i' } },
          ['<C-c>'] = { 'cancel', defer_to_completion = true },
          ['@'] = { 'mention_file', mode = 'i' },
          ['~'] = { 'mention', mode = 'i' },
          ['/'] = { 'slash_commands', mode = 'i' },
          ['#'] = { 'context_items', mode = 'i' },
          ['<M-v>'] = { 'paste_image', mode = 'i' },
          ['<up>'] = { 'prev_prompt_history', mode = { 'n', 'i' }, defer_to_completion = true },
          ['<down>'] = { 'next_prompt_history', mode = { 'n', 'i' }, defer_to_completion = true },
          ['<tab>'] = { 'switch_mode', mode = {'n', 'i'} },
          ['<M-r>'] = { 'cycle_variant', mode = { 'n', 'i' } },
        },
        output_window = {
          ['<C-c>'] = { 'cancel' },
          ['i'] = { 'focus_input', 'n' },
          ['<M-r>'] = { 'cycle_variant', mode = { 'n' } },
          ['<leader>cS'] = { 'select_child_session' },
          ['<leader>cD'] = { 'debug_message' },
          ['<leader>cO'] = { 'debug_output' },
          ['<leader>cds'] = { 'debug_session' },
        },
        session_picker = {
          rename_session = { '<C-r>' },
          delete_session = { '<C-d>' },
          new_session = { '<C-s>' },
        },
        timeline_picker = {
          undo = { '<C-u>', mode = { 'i', 'n' } },
          fork = { '<C-f>', mode = { 'i', 'n' } },
        },
        history_picker = {
          delete_entry = { '<C-d>', mode = { 'i', 'n' } },
          clear_all = { '<C-X>', mode = { 'i', 'n' } },
        },
        model_picker = {
          toggle_favorite = { '<C-f>', mode = { 'i', 'n' } },
        },
        mcp_picker = {
          toggle_connection = { '<C-t>', mode = { 'i', 'n' } },
        },
      },
      ui = {
        enable_treesitter_markdown = true,
        position = 'right',
        input_position = 'bottom',
        window_width = 0.40,
        zoom_width = 0.8,
        display_model = true,
        display_context_size = true,
        display_cost = true,
        icons = {
          preset = 'nerdfonts',
        },
        input = {
          min_height = 0.10,
          max_height = 0.25,
          text = {
            wrap = false,
          },
          auto_hide = false,
        },
        picker = {
          snacks_layout = nil
        },
        completion = {
          file_sources = {
            enabled = true,
            preferred_cli_tool = 'server',
            ignore_patterns = {
              '^%.git/',
              '^%.svn/',
              '^%.hg/',
              'node_modules/',
              '%.pyc$',
              '%.o$',
              '%.obj$',
              '%.exe$',
              '%.dll$',
              '%.so$',
              '%.dylib$',
              '%.class$',
              '%.jar$',
              '%.war$',
              '%.ear$',
              'target/',
              'build/',
              'dist/',
              'out/',
              'deps/',
              '%.tmp$',
              '%.temp$',
              '%.log$',
              '%.cache$',
            },
            max_files = 10,
            max_display_length = 50,
          },
        },
      },
    }
  end,
}
