#!/bin/zsh

## Get status
get_status() {
	playback_symbol='$(spt playback --status --format "%s")'
	if [[ playback_symbol == "⏸" ]]; then
		echo ""
	else
		echo "喇"
	fi
}

## Get song
get_song() {
	song=$(spt playback --status --format "%t")
	if [[ -z "$song" ]]; then
		echo "Offline"
	else
		echo "$song"
	fi	
}

## Get artist
get_artist() {
	artist=$(spt playback --status --format "%a")
	if [[ -z "$artist" ]]; then
		echo "Offline"
	else
		echo "$artist"
	fi	
}

## Execute accordingly
if [[ "$1" == "--song" ]]; then
	get_song
elif [[ "$1" == "--artist" ]]; then
	get_artist
elif [[ "$1" == "--status" ]]; then
	get_status
elif [[ "$1" == "--toggle" ]]; then
	spt playback --toggle > /dev/null
elif [[ "$1" == "--next" ]]; then
	spt playback --next > /dev/null
elif [[ "$1" == "--prev" ]]; then
	spt playback --previous > /dev/null
fi
